//
//  WineModels_updated.swift
//  PocketSomm
//
//  Updated models to match the backend's new response envelope.
//  The `WineProfileResponse` no longer expects a `status` field. Instead, it
//  mirrors the payload inside the `data` object returned by the backend.
//

import Foundation

/// The payload for add-favorite-from-photo responses. This mirrors the
/// structure of the `data` field in the backend response.
struct WineProfileResponse: Codable {
    let wineProfile: WineProfile
    let user: UserProfileDTO?

    enum CodingKeys: String, CodingKey {
        case wineProfile = "wine_profile"
        case user
    }
}

/// A structured description of a wine generated by GPT. This model remains
/// unchanged but is included here for completeness.
struct WineProfile: Codable {
    let resolvedName: String?
    let producer: String?
    let country: String?
    let region: String?
    let appellation: String?
    let color: String?
    let grapes: [String]?
    let vintageTypical: String?
    let confidence: String?
    let notes: String?

    enum CodingKeys: String, CodingKey {
        case resolvedName = "resolved_name"
        case producer
        case country
        case region
        case appellation
        case color
        case grapes
        case vintageTypical = "vintage_typical"
        case confidence
        case notes
    }
}
